services:
  postgres:
    image: postgres:15.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    env_file:
      - env.dev

  server:
    build: ./
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - env.dev